repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        name: conventional commit check
        stages: [commit-msg]
        args:
          - --strict
          - --verbose
          - --scopes
          - ci,core,internal,extension
          - chore
          - docs
          - enhance
          - feat
          - fix
          - refactor
          - release
          - test
